name = "RAMS"
uuid = "ed723de6-1c0c-4ea4-9b14-8350b93dae4c"
authors = ["Lucas Sterzinger <lsterzinger@ucdavis.edu>"]
version = "0.1.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
